server:
  port: 8888

spring:
  application:
    name: SERVICE-GATEWAY
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: SERVICE-GATEWAY
        health-check-path: /actuator/health
        health-check-interval: 10s
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
